theme: jekyll-theme-minimal
title: Stat 184 Final
  
Please see the link to the Github Repository, I made the webpage work but could not get R markdown here, only regular markdown, which doesn't run. Link: https://github.com/brittnieyi/stat184final

:)
